---
- name: installing apache server
  ansible.builtin.apt:
    name: apache2
    state: present
- name: installing nginx server
  ansible.builtin.apt:
    name: nginx
    state: present
- name: installing python
  ansible.builtin.apt:
    name: python3
    state: present
